blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»ä½¿ã„æ–¹
    url: https://github.com/Arstchi-multidesigner/3D-Manga-Studios-Issues/discussions
    about: æ“ä½œæ–¹æ³•ã‚„ä»•æ§˜ã®è³ªå•ã¯ã“ã¡ã‚‰
